import 'package:flutter/cupertino.dart';

final emailController = TextEditingController();
final passwordController = TextEditingController();
final nameDataElm = TextEditingController();
final fNameDataElm = TextEditingController();
final sNameDataElm = TextEditingController();
final cityDataElm = TextEditingController();
final addressDataElm = TextEditingController();
final phoneNumDataElm = TextEditingController();
final emailDataElm = TextEditingController();
final nameReg     = TextEditingController();
final fNameReg    = TextEditingController();
final sNameReg    = TextEditingController();
final cityReg     =  TextEditingController();
final addressReg  = TextEditingController();
final phoneNumReg = TextEditingController();
final emailReg    = TextEditingController();
final passwordReg = TextEditingController();
//final emailController = TextEditingController();